### ISSUE TITLE
Added Input Bar

### ISSUE THREAD

**Issue by SanskrutiPalekar** [Diversion2k22/Embellish#35]
**Is your feature request related to a problem? Please describe.**
Added input bar 

**Describe alternatives you've considered**
Added input bar in components section

**Additional context**
![Input bar](https://user-images.githubusercontent.com/94389020/156919761-fc77ceea-253a-423d-81fb-de7995357e02.jpg)

**Comment by siddhi-244** [comment]
Go for it!
